#!/usr/bin/env python3
"""Generate a Kora 2.0 Kafka consumer (@KafkaListener) for Java or Kotlin.

Emits one listener class with exactly ONE @KafkaListener method, the matching
kafka.consumer.<name> HOCON section and, optionally, an integration test.

Kora 2.0 facts this generator encodes:
  * group io.koraframework, artifact io.koraframework:kafka, BOM io.koraframework:kora-bom
  * @KafkaListener lives in io.koraframework.kafka.common.annotation
  * @Component lives in io.koraframework.common.annotation
  * @Nullable is org.jspecify.annotations.Nullable (Java) / a nullable type (Kotlin)
  * contracts are synchronous: no suspend, no reactive types, no Kora Context
  * telemetry.logging.enabled and telemetry.metrics.enabled default to false
  * HOCON has no ${VAR:default}; use a literal followed by ${?VAR}
  * Testcontainers 2.x module is org.testcontainers:testcontainers-kafka

Examples:
  generate_consumer.py --name UserEvent --topics user-events --package com.example
  generate_consumer.py --name Order --topics orders --signature records --lang kotlin
  generate_consumer.py --name Order --topics orders --json --event-name OrderEvent --tests
  generate_consumer.py --name Order --topics orders --dry-run
"""

import argparse
import sys
from pathlib import Path

SIGNATURES = ("value", "keyvalue", "record", "records", "manual")


def render(template: str, **values: str) -> str:
    out = template
    for key, value in values.items():
        out = out.replace("{{" + key + "}}", value)
    return out


# --------------------------------------------------------------------------- Java listener bodies

JAVA_BODIES = {
    "value": """    @KafkaListener("{{CONFIG_PATH}}")
    void process(String value) {
        log.debug("Consuming value");
        handle(value);
    }""",
    "keyvalue": """    @KafkaListener("{{CONFIG_PATH}}")
    void process(String key, String value) {
        log.debug("Consuming key={}", key);
        handle(value);
    }""",
    "record": """    @KafkaListener("{{CONFIG_PATH}}")
    void process(ConsumerRecord<String, String> record) {
        log.debug("Consuming {}-{}@{}", record.topic(), record.partition(), record.offset());
        handle(record.value());
    }""",
    "records": """    @KafkaListener("{{CONFIG_PATH}}")
    void process(ConsumerRecords<String, String> records) {
        log.debug("Consuming a batch of {} records", records.count());
        for (ConsumerRecord<String, String> record : records) {
            handle(record.value());
        }
    }""",
    "manual": """    @KafkaListener("{{CONFIG_PATH}}")
    void process(ConsumerRecord<String, String> record, Consumer<String, String> consumer) {
        handle(record.value());
        consumer.commitSync();
    }""",
}

JAVA_JSON_BODY = """    @Json
    public record {{EVENT}}(String id, String type) {}

    @KafkaListener("{{CONFIG_PATH}}")
    void process(@Json @Nullable {{EVENT}} event, @Nullable Exception exception) {
        if (exception != null) {
            log.warn("Failed to deserialize record", exception);
            return;
        }
        if (event == null) {
            log.warn("Received a tombstone without an exception");
            return;
        }
        handle(event);
    }"""

JAVA_IMPORTS = {
    "value": [],
    "keyvalue": [],
    "record": ["org.apache.kafka.clients.consumer.ConsumerRecord"],
    "records": [
        "org.apache.kafka.clients.consumer.ConsumerRecord",
        "org.apache.kafka.clients.consumer.ConsumerRecords",
    ],
    "manual": [
        "org.apache.kafka.clients.consumer.Consumer",
        "org.apache.kafka.clients.consumer.ConsumerRecord",
    ],
}

JAVA_LISTENER = """package {{PACKAGE}}.listener;

import io.koraframework.common.annotation.Component;
import io.koraframework.kafka.common.annotation.KafkaListener;
{{IMPORTS}}import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * Kafka consumer for topics: {{TOPICS_DOC}}
 * Config path: {{CONFIG_PATH}}
 *
 * One @KafkaListener method per config path — a second one on the same path starts a second
 * consumer in the same group. Generated by the kora-kafka-consumer skill.
 */
@Component
public final class {{CLASS}} {

    private static final Logger log = LoggerFactory.getLogger({{CLASS}}.class);

    private final AtomicInteger processed = new AtomicInteger();

{{BODY}}

    private void handle({{PAYLOAD_TYPE}} payload) {
        processed.incrementAndGet();
        // TODO business logic — runs on the poll thread, keep it under max.poll.interval.ms
    }

    public int processedCount() {
        return processed.get();
    }
}
"""

# ------------------------------------------------------------------------- Kotlin listener bodies

KOTLIN_BODIES = {
    "value": """    @KafkaListener("{{CONFIG_PATH}}")
    fun process(value: String) {
        log.debug("Consuming value")
        handle(value)
    }""",
    "keyvalue": """    @KafkaListener("{{CONFIG_PATH}}")
    fun process(key: String, value: String) {
        log.debug("Consuming key={}", key)
        handle(value)
    }""",
    "record": """    @KafkaListener("{{CONFIG_PATH}}")
    fun process(record: ConsumerRecord<String, String>) {
        log.debug("Consuming {}-{}@{}", record.topic(), record.partition(), record.offset())
        handle(record.value())
    }""",
    "records": """    @KafkaListener("{{CONFIG_PATH}}")
    fun process(records: ConsumerRecords<String, String>) {
        log.debug("Consuming a batch of {} records", records.count())
        records.forEach { handle(it.value()) }
    }""",
    "manual": """    @KafkaListener("{{CONFIG_PATH}}")
    fun process(record: ConsumerRecord<String, String>, consumer: Consumer<String, String>) {
        handle(record.value())
        consumer.commitSync()
    }""",
}

KOTLIN_JSON_BODY = """    @Json
    data class {{EVENT}}(val id: String, val type: String)

    @KafkaListener("{{CONFIG_PATH}}")
    fun process(@Json event: {{EVENT}}?, exception: Exception?) {
        if (exception != null) {
            log.warn("Failed to deserialize record", exception)
            return
        }
        if (event == null) {
            log.warn("Received a tombstone without an exception")
            return
        }
        handle(event)
    }"""

KOTLIN_IMPORTS = {
    "value": [],
    "keyvalue": [],
    "record": ["org.apache.kafka.clients.consumer.ConsumerRecord"],
    "records": ["org.apache.kafka.clients.consumer.ConsumerRecords"],
    "manual": [
        "org.apache.kafka.clients.consumer.Consumer",
        "org.apache.kafka.clients.consumer.ConsumerRecord",
    ],
}

KOTLIN_LISTENER = """package {{PACKAGE}}.listener

import io.koraframework.common.annotation.Component
import io.koraframework.kafka.common.annotation.KafkaListener
{{IMPORTS}}import org.slf4j.LoggerFactory
import java.util.concurrent.atomic.AtomicInteger

/**
 * Kafka consumer for topics: {{TOPICS_DOC}}
 * Config path: {{CONFIG_PATH}}
 *
 * One @KafkaListener function per config path. Listener functions are plain `fun` — Kora 2.0
 * contracts are synchronous. Generated by the kora-kafka-consumer skill.
 */
@Component
class {{CLASS}} {

    private val log = LoggerFactory.getLogger({{CLASS}}::class.java)

    private val processed = AtomicInteger()

{{BODY}}

    private fun handle(payload: {{PAYLOAD_TYPE}}) {
        processed.incrementAndGet()
        // TODO business logic — runs on the poll thread, keep it under max.poll.interval.ms
    }

    fun processedCount(): Int = processed.get()
}
"""

# -------------------------------------------------------------------------------------- the tests

JAVA_TEST = """package {{PACKAGE}}.listener;

import io.goodforgod.testcontainers.extensions.ContainerMode;
import io.goodforgod.testcontainers.extensions.kafka.ConnectionKafka;
import io.goodforgod.testcontainers.extensions.kafka.Event;
import io.goodforgod.testcontainers.extensions.kafka.KafkaConnection;
import io.goodforgod.testcontainers.extensions.kafka.TestcontainersKafka;
import io.goodforgod.testcontainers.extensions.kafka.Topics;
import io.koraframework.application.graph.Lifecycle;
import io.koraframework.common.annotation.Tag;
import io.koraframework.test.extension.junit5.KoraAppTest;
import io.koraframework.test.extension.junit5.KoraAppTestConfigModifier;
import io.koraframework.test.extension.junit5.KoraConfigModification;
import io.koraframework.test.extension.junit5.TestComponent;
import {{PACKAGE}}.Application;
import org.awaitility.Awaitility;
import org.junit.jupiter.api.Test;

import java.time.Duration;

/**
 * Integration test for {{CLASS}}.
 *
 * The tagged Lifecycle injection is what pulls the generated consumer container into the test
 * graph — without it @KoraAppTest prunes the container and the listener never starts.
 *
 * Requires: io.koraframework:test-junit5, io.goodforgod:testcontainers-extensions-kafka,
 * org.awaitility:awaitility. The raw Testcontainers module is org.testcontainers:testcontainers-kafka
 * in Testcontainers 2.x, not org.testcontainers:kafka.
 */
@TestcontainersKafka(mode = ContainerMode.PER_RUN, topics = @Topics({"{{TOPIC}}"}))
@KoraAppTest(Application.class)
class {{CLASS}}Tests implements KoraAppTestConfigModifier {

    @ConnectionKafka
    private KafkaConnection connection;

    @Tag({{CLASS}}Module.{{CLASS}}ProcessTag.class)
    @TestComponent
    private Lifecycle consumerLifecycle;

    @TestComponent
    private {{CLASS}} listener;

    @Override
    public KoraConfigModification config() {
        return KoraConfigModification.ofSystemProperty(
            "KAFKA_BOOTSTRAP", connection.params().bootstrapServers());
    }

    @Test
    void consumesRecord() {
        connection.send("{{TOPIC}}", Event.ofValueAndRandomKey({{SAMPLE_JAVA}}));

        Awaitility.await()
            .atMost(Duration.ofSeconds(20))
            .until(() -> listener.processedCount() >= 1);
    }
}
"""

KOTLIN_TEST = """package {{PACKAGE}}.listener

import io.goodforgod.testcontainers.extensions.ContainerMode
import io.goodforgod.testcontainers.extensions.kafka.ConnectionKafka
import io.goodforgod.testcontainers.extensions.kafka.Event
import io.goodforgod.testcontainers.extensions.kafka.KafkaConnection
import io.goodforgod.testcontainers.extensions.kafka.TestcontainersKafka
import io.goodforgod.testcontainers.extensions.kafka.Topics
import io.koraframework.application.graph.Lifecycle
import io.koraframework.common.annotation.Tag
import io.koraframework.test.extension.junit5.KoraAppTest
import io.koraframework.test.extension.junit5.KoraAppTestConfigModifier
import io.koraframework.test.extension.junit5.KoraConfigModification
import io.koraframework.test.extension.junit5.TestComponent
import {{PACKAGE}}.Application
import org.awaitility.Awaitility
import org.junit.jupiter.api.Test
import java.time.Duration

/**
 * Integration test for {{CLASS}}.
 *
 * The tagged Lifecycle injection is what pulls the generated consumer container into the test
 * graph — without it @KoraAppTest prunes the container and the listener never starts.
 *
 * Tests are ordinary functions: Kora 2.0 contracts are synchronous, so no runTest and no
 * coroutine dispatcher belong here.
 */
@TestcontainersKafka(mode = ContainerMode.PER_RUN, topics = Topics("{{TOPIC}}"))
@KoraAppTest(Application::class)
class {{CLASS}}Tests : KoraAppTestConfigModifier {

    @ConnectionKafka
    lateinit var connection: KafkaConnection

    @Tag({{CLASS}}Module.{{CLASS}}ProcessTag::class)
    @TestComponent
    lateinit var consumerLifecycle: Lifecycle

    @TestComponent
    lateinit var listener: {{CLASS}}

    override fun config(): KoraConfigModification =
        KoraConfigModification.ofSystemProperty("KAFKA_BOOTSTRAP", connection.params().bootstrapServers())

    @Test
    fun consumesRecord() {
        connection.send("{{TOPIC}}", Event.ofValueAndRandomKey({{SAMPLE_KOTLIN}}))

        Awaitility.await()
            .atMost(Duration.ofSeconds(20))
            .until { listener.processedCount() >= 1 }
    }
}
"""

# ------------------------------------------------------------------------------------- the config

CONFIG = """# Kora 2.0 Kafka consumer configuration for {{CLASS}}
# Generated by the kora-kafka-consumer skill.
#
# HOCON has no ${VAR:default}. Write the literal first, then override it with ${?VAR}.

kafka {
  consumer {
    {{NAME}} {
      topics = [{{TOPICS}}]

      pollTimeout = 5s
      backoffTimeout = 15s
      shutdownWait = 30s
      threads = 1
      allowEmptyRecords = false

      driverProperties {
        "bootstrap.servers" = "localhost:9092"
        "bootstrap.servers" = ${?KAFKA_BOOTSTRAP}

        # group.id present => subscribe strategy. Remove it for the assign strategy, which
        # requires topics (no topicsPattern) and never commits offsets.
        "group.id" = "{{GROUP_ID}}"

        # Where a brand-new consumer group starts. The Kora `offset` key applies to assign mode only.
        "auto.offset.reset" = "earliest"

        # Leave enable.auto.commit unset so Kora commits after the handler returns.
        "max.poll.records" = 500
        "max.poll.interval.ms" = 300000
      }

      telemetry {
        # Both default to false in Kora 2.0 — logging.enabled also gates the container's own
        # lifecycle log lines.
        logging.enabled = true
        metrics {
          enabled = true
          slo = [1, 10, 50, 100, 200, 500, 1000, 2000, 5000, 10000]
          tags {
            "consumer-type" = "{{NAME}}"
          }
        }
        tracing.enabled = true
      }
    }
  }
}

logging.levels {
  "ROOT" = "INFO"
  "io.koraframework" = "INFO"
  "{{PACKAGE}}" = "DEBUG"
}
"""


def build_listener(lang: str, cls: str, package: str, config_path: str, topics: list[str],
                   signature: str, is_json: bool, event: str) -> str:
    kotlin = lang == "kotlin"
    topics_doc = ", ".join(topics)

    if is_json:
        body_tpl = KOTLIN_JSON_BODY if kotlin else JAVA_JSON_BODY
        imports = [
            "io.koraframework.json.common.annotation.Json",
        ]
        if not kotlin:
            imports.append("org.jspecify.annotations.Nullable")
        payload_type = event
    else:
        body_tpl = (KOTLIN_BODIES if kotlin else JAVA_BODIES)[signature]
        imports = list((KOTLIN_IMPORTS if kotlin else JAVA_IMPORTS)[signature])
        payload_type = "String"

    import_block = "".join("import %s%s\n" % (i, "" if kotlin else ";") for i in sorted(imports))
    body = render(body_tpl, CONFIG_PATH=config_path, EVENT=event)

    return render(
        KOTLIN_LISTENER if kotlin else JAVA_LISTENER,
        PACKAGE=package,
        CLASS=cls,
        CONFIG_PATH=config_path,
        TOPICS_DOC=topics_doc,
        IMPORTS=import_block,
        BODY=body,
        PAYLOAD_TYPE=payload_type,
    )


def build_test(lang: str, cls: str, package: str, topic: str, is_json: bool, event: str) -> str:
    if is_json:
        sample_java = '"{\\"id\\":\\"1\\",\\"type\\":\\"created\\"}"'
        sample_kotlin = '"""{"id":"1","type":"created"}"""'
    else:
        sample_java = '"payload"'
        sample_kotlin = '"payload"'
    return render(
        KOTLIN_TEST if lang == "kotlin" else JAVA_TEST,
        PACKAGE=package,
        CLASS=cls,
        TOPIC=topic,
        EVENT=event,
        SAMPLE_JAVA=sample_java,
        SAMPLE_KOTLIN=sample_kotlin,
    )


def build_config(cls: str, name: str, package: str, topics: list[str], group_id: str) -> str:
    return render(
        CONFIG,
        CLASS=cls,
        NAME=name,
        PACKAGE=package,
        GROUP_ID=group_id,
        TOPICS=", ".join('"%s"' % t for t in topics),
    )


def emit(path: Path, content: str, dry_run: bool, skip_if_exists: bool = False) -> None:
    if dry_run:
        print("[dry-run] would write %s (%d bytes)" % (path, len(content.encode("utf-8"))))
        return
    if skip_if_exists and path.exists():
        print("exists, not overwritten: %s" % path)
        print("--- append the following manually ---")
        print(content)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print("wrote %s" % path)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a Kora 2.0 Kafka consumer (@KafkaListener)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--name", "-n", required=True,
                        help='Listener name; "Listener" is appended when missing (e.g. UserEvent)')
    parser.add_argument("--topics", "-t", required=True,
                        help="Comma-separated Kafka topics")
    parser.add_argument("--package", "-p", default="com.example",
                        help="Base package (default: com.example)")
    parser.add_argument("--lang", "-l", choices=["java", "kotlin"], default="java",
                        help="Target language (default: java)")
    parser.add_argument("--output", "-o", default="src/main",
                        help="Main source-set directory (default: src/main)")
    parser.add_argument("--signature", "-s", choices=SIGNATURES, default="record",
                        help="Listener signature: value | keyvalue | record | records | manual "
                             "(default: record). Ignored with --json, which always uses the "
                             "nullable payload + nullable Exception shape.")
    parser.add_argument("--json", action="store_true",
                        help="Generate a @Json payload record and the deserialization-error shape")
    parser.add_argument("--event-name", help="Payload type name for --json (default: <Name>Event)")
    parser.add_argument("--group-id", help="Kafka group.id (default: <name>-group)")
    parser.add_argument("--tests", action="store_true", help="Also generate an integration test")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be written without touching the filesystem")

    args = parser.parse_args()

    topics = [t.strip() for t in args.topics.split(",") if t.strip()]
    if not topics:
        parser.error("--topics must name at least one topic")

    cls = args.name if args.name.endswith("Listener") else args.name + "Listener"
    name = cls[0].lower() + cls[1:]
    config_path = "kafka.consumer." + name
    group_id = args.group_id or (name + "-group")
    event = args.event_name or (cls[:-len("Listener")] + "Event")

    lang_dir = "kotlin" if args.lang == "kotlin" else "java"
    ext = "kt" if args.lang == "kotlin" else "java"
    package_dir = args.package.replace(".", "/")

    main_root = Path(args.output)
    listener_path = main_root / lang_dir / package_dir / "listener" / ("%s.%s" % (cls, ext))
    config_path_file = main_root / "resources" / "application.conf"
    test_path = (main_root.parent / "test" / lang_dir / package_dir / "listener"
                 / ("%sTests.%s" % (cls, ext)))

    emit(listener_path,
         build_listener(args.lang, cls, args.package, config_path, topics,
                        args.signature, args.json, event),
         args.dry_run)

    emit(config_path_file,
         build_config(cls, name, args.package, topics, group_id),
         args.dry_run, skip_if_exists=True)

    if args.tests:
        emit(test_path,
             build_test(args.lang, cls, args.package, topics[0], args.json, event),
             args.dry_run)

    print("")
    print("class        : %s.listener.%s" % (args.package, cls))
    print("config path  : %s" % config_path)
    print("topics       : %s" % ", ".join(topics))
    print("group.id     : %s" % group_id)
    print("signature    : %s" % ("json (nullable payload + nullable Exception)"
                                 if args.json else args.signature))
    print("generated tag: %sModule.%sProcessTag" % (cls, cls))
    print("")
    print("Next: add KafkaModule (and JsonModule for --json) to the @KoraApp interface,")
    print("      point bootstrap.servers at your broker, then ./gradlew build")


if __name__ == "__main__":
    main()
