#!/usr/bin/env python3
"""
Kora Kafka Producer Generator

Generates Kafka producer interface templates based on provided configuration.

Usage:
    python generate_producer.py --name MyPublisher --topics my-topic [--package com.example] [--lang kotlin]
"""

import argparse
import sys
from pathlib import Path


def generate_producer(name: str, topics: list[str], package: str, lang: str, output_dir: str, with_tests: bool = False) -> None:
    """Generate Kafka producer interface."""
    
    is_kotlin = lang == "kotlin"
    package_path = package.replace(".", "/")
    interface_name = name if name.endswith("Publisher") else f"{name}Publisher"
    file_ext = "kt" if is_kotlin else "java"
    
    # Create output directory
    subdir = "kotlin" if is_kotlin else "java"
    output_path = Path(output_dir) / subdir / package_path / "publisher"
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Create test output directory if needed
    if with_tests:
        test_subdir = "kotlin" if is_kotlin else "java"
        test_output_path = Path(output_dir).parent / "test" / test_subdir / package_path / "publisher"
        test_output_path.mkdir(parents=True, exist_ok=True)
    
    if is_kotlin:
        topic_methods = ""
        for topic in topics:
            topic_const = topic.upper().replace("-", "_").replace(".", "_")
            topic_methods += f'''
    /**
     * Send message to {topic}
     * 
     * @param value Message value
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    fun send(value: String)
    
    /**
     * Send message with key to {topic}
     * 
     * @param key Message key
     * @param value Message value
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    fun send(key: String, value: String)
    
    /**
     * Send message with metadata response
     * 
     * @param value Message value
     * @return RecordMetadata
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    fun sendWithMeta(value: String): RecordMetadata
'''
        
        producer_code = f'''package {package}.publisher

import java.util.concurrent.Future
import org.apache.kafka.clients.producer.RecordMetadata
import ru.tinkoff.kora.kafka.common.annotation.KafkaPublisher
import ru.tinkoff.kora.kafka.common.annotation.KafkaPublisher.Topic

/**
 * Kafka producer for topics: {', '.join(topics)}
 * Generated by kora-kafka generator
 */
@KafkaPublisher("kafka.producer.{interface_name.lower()}")
interface {interface_name} {{{topic_methods}
}}
'''
    else:
        topic_methods = ""
        for topic in topics:
            topic_const = topic.upper().replace("-", "_").replace(".", "_")
            topic_methods += f'''
    /**
     * Send message to {topic}
     * 
     * @param value Message value
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    void send(String value);
    
    /**
     * Send message with key to {topic}
     * 
     * @param key Message key
     * @param value Message value
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    void send(String key, String value);
    
    /**
     * Send message with metadata response
     * 
     * @param value Message value
     * @return RecordMetadata
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    RecordMetadata sendWithMeta(String value);
'''
        
        producer_code = f'''package {package}.publisher;

import java.util.concurrent.Future;
import org.apache.kafka.clients.producer.RecordMetadata;
import ru.tinkoff.kora.kafka.common.annotation.KafkaPublisher;
import ru.tinkoff.kora.kafka.common.annotation.KafkaPublisher.Topic;

/**
 * Kafka producer for topics: {', '.join(topics)}
 * Generated by kora-kafka generator
 */
@KafkaPublisher("kafka.producer.{interface_name.lower()}")
public interface {interface_name} {{{topic_methods}
}}
'''
    
    # Write producer interface
    producer_file = output_path / f"{interface_name}.{file_ext}"
    producer_file.write_text(producer_code)
    print(f"✓ Generated producer: {producer_file}")
    
    # Generate config snippet
    topic_configs = ""
    for topic in topics:
        topic_const = topic.upper().replace("-", "_").replace(".", "_")
        topic_configs += f'''      {topic_const} {{
        topic = "{topic}"
      }}
'''
    
    config_snippet = f'''
# Producer configuration for {interface_name}
kafka {{
  producer {{
    {interface_name.lower()} {{
      driverProperties {{
        "bootstrap.servers" = ${{KAFKA_BOOTSTRAP_SERVERS:"localhost:9092"}}
        "acks" = "all"
        "retries" = 3
        "linger.ms" = 5
      }}
{topic_configs}
      telemetry {{
        logging {{
          enabled = true
        }}
        metrics {{
          enabled = true
        }}
        tracing {{
          enabled = true
        }}
      }}
    }}
  }}
}}
'''
    
    config_file = output_path / f"{interface_name.lower()}.conf"
    config_file.write_text(config_snippet)
    print(f"✓ Generated config snippet: {config_file}")
    
    # Generate test class if requested
    if with_tests:
        test_class_name = f"{interface_name}Tests"
        test_file_ext = "kt" if is_kotlin else "java"
        topic_name = topics[0]  # Use first topic for tests
        
        if is_kotlin:
            test_code = f'''package {package}.publisher

import org.apache.kafka.clients.consumer.ConsumerConfig
import org.apache.kafka.clients.consumer.KafkaConsumer
import org.apache.kafka.common.serialization.StringDeserializer
import org.jetbrains.annotations.NotNull
import org.json.JSONObject
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import org.testcontainers.containers.KafkaContainer
import org.testcontainers.junit.jupiter.Container
import org.testcontainers.junit.jupiter.Testcontainers
import org.testcontainers.utility.DockerImageName
import ru.tinkoff.kora.test.extension.junit5.*
import java.time.Duration
import java.util.Properties

@Testcontainers
@KoraAppTest(Application::class)
class {test_class_name} : KoraAppTestConfigModifier {{

    companion object {{
        @Container
        @JvmStatic
        val KAFKA = KafkaContainer(
            DockerImageName.parse("confluentinc/cp-kafka:7.5.0")
        ).withStartupTimeout(Duration.ofSeconds(60))
    }}

    @TestComponent
    private lateinit var publisher: {interface_name}

    @NotNull
    override fun config(): KoraConfigModification {{
        return KoraConfigModification.ofSystemProperty(
            "KAFKA_BOOTSTRAP",
            KAFKA.bootstrapServers
        )
    }}

    @Test
    fun `should send message`() {{
        // given
        val message = "test-message-${{System.currentTimeMillis()}}"
        val consumerProps = createConsumerProps()

        // when
        publisher.send(message)

        // then
        KafkaConsumer<String, String>(consumerProps).use {{ consumer ->
            consumer.subscribe(listOf("{topic_name}"))
            val records = consumer.poll(Duration.ofSeconds(5))
            assertTrue(records.isNotEmpty())
            assertEquals(message, records.iterator().next().value())
        }}
    }}

    @Test
    fun `should send json message`() {{
        // given
        val event = JSONObject()
            .put("id", "test-123")
            .put("name", "Test Event")
        val consumerProps = createConsumerProps()

        // when
        publisher.send(event.toString())

        // then
        KafkaConsumer<String, String>(consumerProps).use {{ consumer ->
            consumer.subscribe(listOf("{topic_name}"))
            val records = consumer.poll(Duration.ofSeconds(5))
            assertTrue(records.isNotEmpty())
            val json = JSONObject(records.iterator().next().value())
            assertEquals("test-123", json.getString("id"))
        }}
    }}

    private fun createConsumerProps(): Properties {{
        return Properties().apply {{
            put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, KAFKA.bootstrapServers)
            put(ConsumerConfig.GROUP_ID_CONFIG, "{interface_name.lower()}-test-group")
            put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer::class.java.name)
            put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer::class.java.name)
            put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest")
        }}
    }}
}}
'''
        else:
            test_code = f'''package {package}.publisher;

import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.jetbrains.annotations.NotNull;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.KafkaContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;
import ru.tinkoff.kora.test.extension.junit5.*;

import java.time.Duration;
import java.util.List;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.*;

@Testcontainers
@KoraAppTest(Application.class)
class {test_class_name}Tests implements KoraAppTestConfigModifier {{

    @Container
    static final KafkaContainer KAFKA = new KafkaContainer(
        DockerImageName.parse("confluentinc/cp-kafka:7.5.0")
    ).withStartupTimeout(Duration.ofSeconds(60));

    @TestComponent
    private {interface_name} publisher;

    @NotNull
    @Override
    public KoraConfigModification config() {{
        return KoraConfigModification.ofSystemProperty(
            "KAFKA_BOOTSTRAP",
            KAFKA.getBootstrapServers()
        );
    }}

    @Test
    void shouldSendMessage() {{
        // given
        var message = "test-message-" + System.currentTimeMillis();
        var consumerProps = createConsumerProps();

        // when
        publisher.send(message);

        // then
        try (var consumer = new KafkaConsumer<String, String>(consumerProps)) {{
            consumer.subscribe(List.of("{topic_name}"));
            var records = consumer.poll(Duration.ofSeconds(5));
            assertFalse(records.isEmpty());
            assertEquals(message, records.iterator().next().value());
        }}
    }}

    @Test
    void shouldSendJsonMessage() {{
        // given
        var event = new JSONObject()
            .put("id", "test-123")
            .put("name", "Test Event");
        var consumerProps = createConsumerProps();

        // when
        publisher.send(event.toString());

        // then
        try (var consumer = new KafkaConsumer<String, String>(consumerProps)) {{
            consumer.subscribe(List.of("{topic_name}"));
            var records = consumer.poll(Duration.ofSeconds(5));
            assertFalse(records.isEmpty());
            var json = new JSONObject(records.iterator().next().value());
            assertEquals("test-123", json.getString("id"));
        }}
    }}

    private Properties createConsumerProps() {{
        var props = new Properties();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, KAFKA.getBootstrapServers());
        props.put(ConsumerConfig.GROUP_ID_CONFIG, "{interface_name.lower()}-test-group");
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        return props;
    }}
}}
'''
        
        test_file = test_output_path / f"{test_class_name}.{test_file_ext}"
        test_file.write_text(test_code)
        print(f"✓ Generated test: {test_file}")
    
    print(f"\n✓ Producer generation complete!")
    print(f"  Interface: {package}.{interface_name}")
    print(f"  Topics: {', '.join(topics)}")
    print(f"  Config path: kafka.producer.{interface_name.lower()}")
    if with_tests:
        print(f"  Tests: {package}.publisher.{test_class_name}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Kafka producer interface for Kora application"
    )
    parser.add_argument(
        "--name",
        required=True,
        help="Producer name (e.g., MyPublisher)"
    )
    parser.add_argument(
        "--topics",
        required=True,
        nargs="+",
        help="Kafka topics to produce (e.g., topic1 topic2)"
    )
    parser.add_argument(
        "--package",
        default="com.example",
        help="Java package name (default: com.example)"
    )
    parser.add_argument(
        "--lang",
        choices=["java", "kotlin"],
        default="java",
        help="Language: java or kotlin (default: java)"
    )
    parser.add_argument(
        "--output",
        default="src/main",
        help="Output directory (default: src/main)"
    )
    parser.add_argument(
        "--with-tests",
        action="store_true",
        help="Generate test class along with producer (default: False)"
    )
    
    args = parser.parse_args()
    
    try:
        generate_producer(
            name=args.name,
            topics=args.topics,
            package=args.package,
            lang=args.lang,
            output_dir=args.output,
            with_tests=args.with_tests
        )
    except Exception as e:
        print(f"✗ Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
