#!/usr/bin/env python3
"""
Kora Kafka Producer Generator

Generates Kafka producer interface templates based on provided configuration.

Usage:
    python generate_producer.py --name MyPublisher --topics my-topic [--package com.example] [--lang kotlin]
"""

import argparse
import sys
from pathlib import Path


def generate_producer(name: str, topics: list[str], package: str, lang: str, output_dir: str, with_tests: bool = False) -> None:
    """Generate Kafka producer interface."""
    
    is_kotlin = lang == "kotlin"
    package_path = package.replace(".", "/")
    interface_name = name if name.endswith("Publisher") else f"{name}Publisher"
    file_ext = "kt" if is_kotlin else "java"
    
    # Create output directory
    subdir = "kotlin" if is_kotlin else "java"
    output_path = Path(output_dir) / subdir / package_path / "publisher"
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Create test output directory if needed
    if with_tests:
        test_subdir = "kotlin" if is_kotlin else "java"
        test_output_path = Path(output_dir).parent / "test" / test_subdir / package_path / "publisher"
        test_output_path.mkdir(parents=True, exist_ok=True)
    
    if is_kotlin:
        topic_methods = ""
        for topic in topics:
            topic_const = topic.upper().replace("-", "_").replace(".", "_")
            topic_methods += f'''
    /**
     * Send message to {topic}
     * 
     * @param value Message value
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    fun send(value: String)
    
    /**
     * Send message with key to {topic}
     * 
     * @param key Message key
     * @param value Message value
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    fun send(key: String, value: String)
    
    /**
     * Send message with metadata response
     * 
     * @param value Message value
     * @return RecordMetadata
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    fun sendWithMeta(value: String): RecordMetadata
'''
        
        producer_code = f'''package {package}.publisher

import java.util.concurrent.Future
import org.apache.kafka.clients.producer.RecordMetadata
import ru.tinkoff.kora.kafka.common.annotation.KafkaPublisher
import ru.tinkoff.kora.kafka.common.annotation.KafkaPublisher.Topic

/**
 * Kafka producer for topics: {', '.join(topics)}
 * Generated by kora-kafka generator
 */
@KafkaPublisher("kafka.producer.{interface_name.lower()}")
interface {interface_name} {{{topic_methods}
}}
'''
    else:
        topic_methods = ""
        for topic in topics:
            topic_const = topic.upper().replace("-", "_").replace(".", "_")
            topic_methods += f'''
    /**
     * Send message to {topic}
     * 
     * @param value Message value
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    void send(String value);
    
    /**
     * Send message with key to {topic}
     * 
     * @param key Message key
     * @param value Message value
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    void send(String key, String value);
    
    /**
     * Send message with metadata response
     * 
     * @param value Message value
     * @return RecordMetadata
     */
    @Topic("kafka.producer.{interface_name.lower()}.{topic_const}")
    RecordMetadata sendWithMeta(String value);
'''
        
        producer_code = f'''package {package}.publisher;

import java.util.concurrent.Future;
import org.apache.kafka.clients.producer.RecordMetadata;
import ru.tinkoff.kora.kafka.common.annotation.KafkaPublisher;
import ru.tinkoff.kora.kafka.common.annotation.KafkaPublisher.Topic;

/**
 * Kafka producer for topics: {', '.join(topics)}
 * Generated by kora-kafka generator
 */
@KafkaPublisher("kafka.producer.{interface_name.lower()}")
public interface {interface_name} {{{topic_methods}
}}
'''
    
    # Write producer interface
    producer_file = output_path / f"{interface_name}.{file_ext}"
    producer_file.write_text(producer_code)
    print(f"✓ Generated producer: {producer_file}")
    
    # Generate config snippet
    topic_configs = ""
    for topic in topics:
        topic_const = topic.upper().replace("-", "_").replace(".", "_")
        topic_configs += f'''      {topic_const} {{
        topic = "{topic}"
      }}
'''
    
    config_snippet = f'''
# Producer configuration for {interface_name}
kafka {{
  producer {{
    {interface_name.lower()} {{
      driverProperties {{
        "bootstrap.servers" = ${{KAFKA_BOOTSTRAP_SERVERS:"localhost:9092"}}
        "acks" = "all"
        "retries" = 3
        "linger.ms" = 5
      }}
{topic_configs}
      telemetry {{
        logging {{
          enabled = true
        }}
        metrics {{
          enabled = true
        }}
        tracing {{
          enabled = true
        }}
      }}
    }}
  }}
}}
'''
    
    config_file = output_path / f"{interface_name.lower()}.conf"
    config_file.write_text(config_snippet)
    print(f"✓ Generated config snippet: {config_file}")
    
    # Generate test class if requested
    if with_tests:
        test_class_name = f"{interface_name}Tests"
        test_file_ext = "kt" if is_kotlin else "java"
        topic_name = topics[0]  # Use first topic for tests
        
        if is_kotlin:
            test_code = f'''package {package}.publisher

import io.goodforgod.testcontainers.extensions.ContainerMode
import io.goodforgod.testcontainers.extensions.kafka.*
import org.jetbrains.annotations.NotNull
import org.json.JSONObject
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import ru.tinkoff.kora.test.extension.junit5.*

@TestcontainersKafka(
    mode = ContainerMode.PER_RUN,
    topics = [Topics(["{topic_name}"])]
)
@KoraAppTest(Application::class)
class {test_class_name} : KoraAppTestConfigModifier {{

    @ConnectionKafka
    private lateinit var connection: KafkaConnection

    @TestComponent
    private lateinit var publisher: {interface_name}

    @NotNull
    override fun config(): KoraConfigModification {{
        return KoraConfigModification.ofSystemProperty(
            "KAFKA_BOOTSTRAP",
            connection.params().bootstrapServers()
        )
    }}

    @Test
    fun `should send message`() {{
        // given
        val consumer = connection.subscribe("{topic_name}")
        val message = "test-message-${{System.currentTimeMillis()}}"

        // when
        publisher.send(message)

        // then
        val received = consumer.assertReceivedAtLeast(1)[0]
        assertNull(received.key())
        assertEquals(message, received.value())
    }}

    @Test
    fun `should send json message`() {{
        // given
        val consumer = connection.subscribe("{topic_name}")
        val event = JSONObject()
            .put("id", "test-123")
            .put("name", "Test Event")

        // when
        publisher.send(event.toString())

        // then
        val received = consumer.assertReceivedAtLeast(1)[0]
        val json = received.value().asJson()
        assertEquals("test-123", json.getString("id"))
    }}
}}
'''
        else:
            test_code = f'''package {package}.publisher;

import io.goodforgod.testcontainers.extensions.ContainerMode;
import io.goodforgod.testcontainers.extensions.kafka.*;
import org.jetbrains.annotations.NotNull;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import ru.tinkoff.kora.test.extension.junit5.*;

import static org.junit.jupiter.api.Assertions.*;

@TestcontainersKafka(
    mode = ContainerMode.PER_RUN,
    topics = @Topics({{ "{topic_name}" }})
)
@KoraAppTest(Application.class)
class {test_class_name}Tests implements KoraAppTestConfigModifier {{

    @ConnectionKafka
    private KafkaConnection connection;

    @TestComponent
    private {interface_name} publisher;

    @NotNull
    @Override
    public KoraConfigModification config() {{
        return KoraConfigModification.ofSystemProperty(
            "KAFKA_BOOTSTRAP",
            connection.params().bootstrapServers()
        );
    }}

    @Test
    void shouldSendMessage() {{
        // given
        var consumer = connection.subscribe("{topic_name}");
        var message = "test-message-" + System.currentTimeMillis();

        // when
        publisher.send(message);

        // then
        var received = consumer.assertReceivedAtLeast(1).get(0);
        assertNull(received.key());
        assertEquals(message, received.value());
    }}

    @Test
    void shouldSendJsonMessage() {{
        // given
        var consumer = connection.subscribe("{topic_name}");
        var event = new JSONObject()
            .put("id", "test-123")
            .put("name", "Test Event");

        // when
        publisher.send(event.toString());

        // then
        var received = consumer.assertReceivedAtLeast(1).get(0);
        var json = received.value().asJson();
        assertEquals("test-123", json.getString("id"));
    }}
}}
'''
        
        test_file = test_output_path / f"{test_class_name}.{test_file_ext}"
        test_file.write_text(test_code)
        print(f"✓ Generated test: {test_file}")
    
    print(f"\n✓ Producer generation complete!")
    print(f"  Interface: {package}.{interface_name}")
    print(f"  Topics: {', '.join(topics)}")
    print(f"  Config path: kafka.producer.{interface_name.lower()}")
    if with_tests:
        print(f"  Tests: {package}.publisher.{test_class_name}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Kafka producer interface for Kora application"
    )
    parser.add_argument(
        "--name",
        required=True,
        help="Producer name (e.g., MyPublisher)"
    )
    parser.add_argument(
        "--topics",
        required=True,
        nargs="+",
        help="Kafka topics to produce (e.g., topic1 topic2)"
    )
    parser.add_argument(
        "--package",
        default="com.example",
        help="Java package name (default: com.example)"
    )
    parser.add_argument(
        "--lang",
        choices=["java", "kotlin"],
        default="java",
        help="Language: java or kotlin (default: java)"
    )
    parser.add_argument(
        "--output",
        default="src/main",
        help="Output directory (default: src/main)"
    )
    parser.add_argument(
        "--with-tests",
        action="store_true",
        help="Generate test class along with producer (default: False)"
    )
    
    args = parser.parse_args()
    
    try:
        generate_producer(
            name=args.name,
            topics=args.topics,
            package=args.package,
            lang=args.lang,
            output_dir=args.output,
            with_tests=args.with_tests
        )
    except Exception as e:
        print(f"✗ Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
