#!/usr/bin/env python3
"""
Kora Kafka Consumer Generator

Generates Kafka consumer listener templates based on provided configuration.

Usage:
    python generate_consumer.py --name MyListener --topics my-topic [--package com.example] [--lang kotlin]
"""

import argparse
import sys
from pathlib import Path


def generate_consumer(name: str, topics: list[str], package: str, lang: str, output_dir: str, with_tests: bool = False) -> None:
    """Generate Kafka consumer listener class."""
    
    is_kotlin = lang == "kotlin"
    package_path = package.replace(".", "/")
    class_name = name if name.endswith("Listener") else f"{name}Listener"
    file_ext = "kt" if is_kotlin else "java"
    
    # Create output directory
    subdir = "kotlin" if is_kotlin else "java"
    output_path = Path(output_dir) / subdir / package_path / "listener"
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Create test output directory if needed
    if with_tests:
        test_subdir = "kotlin" if is_kotlin else "java"
        test_output_path = Path(output_dir).parent / "test" / test_subdir / package_path / "listener"
        test_output_path.mkdir(parents=True, exist_ok=True)
    
    if is_kotlin:
        consumer_code = f'''package {package}.listener

import org.slf4j.LoggerFactory
import ru.tinkoff.kora.common.Component
import ru.tinkoff.kora.kafka.common.annotation.KafkaListener

/**
 * Kafka consumer for topics: {', '.join(topics)}
 * Generated by kora-kafka generator
 */
@Component
class {class_name} {{
    
    private val log = LoggerFactory.getLogger({class_name}::class.java)
    
    /**
     * Process messages from Kafka
     * 
     * @param value Message value
     */
    @KafkaListener("kafka.consumer.{name.lower()}")
    fun process(value: String) {{
        log.info("Received message: {{}}", value)
        // TODO: Implement business logic
    }}
}}
'''
    else:
        consumer_code = f'''package {package}.listener;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.tinkoff.kora.common.Component;
import ru.tinkoff.kora.kafka.common.annotation.KafkaListener;

/**
 * Kafka consumer for topics: {', '.join(topics)}
 * Generated by kora-kafka generator
 */
@Component
public final class {class_name} {{
    
    private static final Logger log = LoggerFactory.getLogger({class_name}.class);
    
    /**
     * Process messages from Kafka
     * 
     * @param value Message value
     */
    @KafkaListener("kafka.consumer.{name.lower()}")
    void process(String value) {{
        log.info("Received message: {{}}", value);
        // TODO: Implement business logic
    }}
}}
'''
    
    # Write consumer class
    consumer_file = output_path / f"{class_name}.{file_ext}"
    consumer_file.write_text(consumer_code)
    print(f"✓ Generated consumer: {consumer_file}")
    
    # Generate config snippet
    config_snippet = f'''
# Consumer configuration for {class_name}
kafka {{
  consumer {{
    {name.lower()} {{
      topics = [{', '.join(f'"{t}"' for t in topics)}]
      pollTimeout = "5s"
      threads = 1
      driverProperties {{
        "bootstrap.servers" = ${{KAFKA_BOOTSTRAP_SERVERS:"localhost:9092"}}
        "group.id" = "{name.lower()}-group"
        "auto.offset.reset" = "latest"
        "enable.auto.commit" = true
      }}
      telemetry {{
        logging {{
          enabled = true
        }}
        metrics {{
          enabled = true
        }}
        tracing {{
          enabled = true
        }}
      }}
    }}
  }}
}}
'''
    
    config_file = output_path / f"{name.lower()}.conf"
    config_file.write_text(config_snippet)
    print(f"✓ Generated config snippet: {config_file}")
    
    # Generate test class if requested
    if with_tests:
        test_class_name = f"{class_name}Tests"
        test_file_ext = "kt" if is_kotlin else "java"
        topic_name = topics[0]  # Use first topic for tests
        
        if is_kotlin:
            test_code = f'''package {package}.listener

import io.goodforgod.testcontainers.extensions.ContainerMode
import io.goodforgod.testcontainers.extensions.kafka.*
import org.jetbrains.annotations.NotNull
import org.json.JSONObject
import org.junit.jupiter.api.Test
import org.testcontainers.shaded.org.awaitility.Awaitility
import ru.tinkoff.kora.application.graph.Lifecycle
import ru.tinkoff.kora.common.Tag
import ru.tinkoff.kora.test.extension.junit5.*
import java.time.Duration
import java.util.concurrent.Executors

@TestcontainersKafka(
    mode = ContainerMode.PER_RUN,
    topics = [Topics(["{topic_name}"])]
)
@KoraAppTest(Application::class)
class {test_class_name} : KoraAppTestConfigModifier {{

    @ConnectionKafka
    private lateinit var connection: KafkaConnection

    @Tag({class_name}Module.{class_name}ProcessTag::class)
    @TestComponent
    private lateinit var consumerLifecycle: Lifecycle

    @TestComponent
    private lateinit var consumer: {class_name}

    @NotNull
    override fun config(): KoraConfigModification {{
        return KoraConfigModification.ofSystemProperty(
            "KAFKA_BOOTSTRAP",
            connection.params().bootstrapServers()
        )
    }}

    @Test
    fun `should process event`() {{
        // given
        val event = JSONObject()
            .put("id", "test-123")
            .put("name", "Test Event")

        // when
        connection.send("{topic_name}", Event.ofValueAndRandomKey(event))

        // then
        Awaitility.await()
            .atMost(Duration.ofSeconds(15))
            .pollExecutorService(Executors.newSingleThreadExecutor())
            .until {{ consumer.processedCount >= 1 }}
    }}
}}
'''
        else:
            test_code = f'''package {package}.listener;

import io.goodforgod.testcontainers.extensions.ContainerMode;
import io.goodforgod.testcontainers.extensions.kafka.*;
import org.jetbrains.annotations.NotNull;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import org.testcontainers.shaded.org.awaitility.Awaitility;
import ru.tinkoff.kora.application.graph.Lifecycle;
import ru.tinkoff.kora.common.Tag;
import ru.tinkoff.kora.test.extension.junit5.*;

import java.time.Duration;
import java.util.concurrent.Executors;

@TestcontainersKafka(
    mode = ContainerMode.PER_RUN,
    topics = @Topics({{ "{topic_name}" }})
)
@KoraAppTest(Application.class)
class {test_class_name}Tests implements KoraAppTestConfigModifier {{

    @ConnectionKafka
    private KafkaConnection connection;

    @Tag({class_name}Module.{class_name}ProcessTag.class)
    @TestComponent
    private Lifecycle consumerLifecycle;

    @TestComponent
    private {class_name} consumer;

    @NotNull
    @Override
    public KoraConfigModification config() {{
        return KoraConfigModification.ofSystemProperty(
            "KAFKA_BOOTSTRAP",
            connection.params().bootstrapServers()
        );
    }}

    @Test
    void shouldProcessEvent() {{
        // given
        var event = new JSONObject()
            .put("id", "test-123")
            .put("name", "Test Event");

        // when
        connection.send("{topic_name}", Event.ofValueAndRandomKey(event));

        // then
        Awaitility.await()
            .atMost(Duration.ofSeconds(15))
            .pollExecutorService(Executors.newSingleThreadExecutor())
            .until(() -> consumer.processedCount() >= 1);
    }}
}}
'''
        
        test_file = test_output_path / f"{test_class_name}.{test_file_ext}"
        test_file.write_text(test_code)
        print(f"✓ Generated test: {test_file}")
    
    print(f"\n✓ Consumer generation complete!")
    print(f"  Class: {package}.{class_name}")
    print(f"  Topics: {', '.join(topics)}")
    print(f"  Config path: kafka.consumer.{name.lower()}")
    if with_tests:
        print(f"  Tests: {package}.listener.{class_name}Tests")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Kafka consumer listener for Kora application"
    )
    parser.add_argument(
        "--name",
        required=True,
        help="Consumer name (e.g., MyListener)"
    )
    parser.add_argument(
        "--topics",
        required=True,
        nargs="+",
        help="Kafka topics to consume (e.g., topic1 topic2)"
    )
    parser.add_argument(
        "--package",
        default="com.example",
        help="Java package name (default: com.example)"
    )
    parser.add_argument(
        "--lang",
        choices=["java", "kotlin"],
        default="java",
        help="Language: java or kotlin (default: java)"
    )
    parser.add_argument(
        "--output",
        default="src/main",
        help="Output directory (default: src/main)"
    )
    parser.add_argument(
        "--with-tests",
        action="store_true",
        help="Generate test class along with consumer (default: False)"
    )
    
    args = parser.parse_args()
    
    try:
        generate_consumer(
            name=args.name,
            topics=args.topics,
            package=args.package,
            lang=args.lang,
            output_dir=args.output,
            with_tests=args.with_tests
        )
    except Exception as e:
        print(f"✗ Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
