#!/usr/bin/env python3
"""
Kora Kafka Consumer Generator

Generates Kafka consumer listener templates based on provided configuration.

Usage:
    python generate_consumer.py --name MyListener --topics my-topic [--package com.example] [--lang kotlin]

Examples:
    python generate_consumer.py --name UserEventListener --topics user-events --package com.example
    python generate_consumer.py --name OrderListener --topics orders,order-updates --package com.example --lang kotlin
    python generate_consumer.py --name JsonListener --topics events --package com.example --json --event-name UserEvent
"""

import argparse
import re
import sys
from pathlib import Path


def generate_consumer(
    name: str,
    topics: list[str],
    package: str,
    lang: str,
    output_dir: str,
    with_tests: bool = False,
    is_json: bool = False,
    event_name: str = None,
    consumer_group_id: str = None,
) -> None:
    """Generate Kafka consumer listener class."""

    is_kotlin = lang == "kotlin"
    package_path = package.replace(".", "/")
    class_name = name if name.endswith("Listener") else f"{name}Listener"
    class_name_lower = class_name[0].lower() + class_name[1:]
    file_ext = "kt" if is_kotlin else "java"

    # Default event name for JSON listeners
    if event_name is None:
        # Extract from class name (e.g., UserEventListener -> UserEvent)
        if class_name.endswith("Listener"):
            event_name = class_name[:-8]  # Remove "Listener"
        else:
            event_name = name

    # Default consumer group ID
    if consumer_group_id is None:
        consumer_group_id = f"{class_name_lower}-group"

    # Create output directory
    subdir = "kotlin" if is_kotlin else "java"
    output_path = Path(output_dir) / subdir / package_path / "listener"
    output_path.mkdir(parents=True, exist_ok=True)

    # Create test output directory if needed
    if with_tests:
        test_subdir = "kotlin" if is_kotlin else "java"
        test_output_path = (
            Path(output_dir).parent / "test" / test_subdir / package_path / "listener"
        )
        test_output_path.mkdir(parents=True, exist_ok=True)

    topics_str = ", ".join(f'"{t}"' for t in topics)
    topics_pattern = topics[0] + "-*" if len(topics) == 1 else ""

    if is_kotlin:
        if is_json:
            consumer_code = generate_kotlin_json_listener(
                package, class_name, class_name_lower, event_name, topics_str
            )
        else:
            consumer_code = generate_kotlin_consumer(
                package, class_name, class_name_lower, topics_str
            )
    else:
        if is_json:
            consumer_code = generate_java_json_listener(
                package, class_name, class_name_lower, event_name, topics_str
            )
        else:
            consumer_code = generate_java_consumer(
                package, class_name, class_name_lower, topics_str
            )

    # Write listener class
    listener_file = output_path / f"{class_name}.{file_ext}"
    listener_file.write_text(consumer_code)
    print(f"Created: {listener_file}")

    # Generate tests
    if with_tests:
        if is_kotlin:
            test_code = generate_kotlin_tests(
                package, class_name, class_name_lower, topics[0]
            )
        else:
            test_code = generate_java_tests(
                package, class_name, class_name_lower, topics[0]
            )

        test_file = test_output_path / f"{class_name}Tests.{file_ext}"
        test_file.write_text(test_code)
        print(f"Created: {test_file}")

    # Generate configuration
    config_code = generate_config(
        class_name_lower, topics_str, topics_pattern, consumer_group_id, package
    )
    config_file = Path(output_dir) / "application.conf"
    if not config_file.exists():
        config_file.write_text(config_code)
        print(f"Created: {config_file}")
    else:
        print(f"Config already exists: {config_file}")
        print("Append the following to your application.conf:")
        print("-" * 60)
        print(config_code)


def generate_java_consumer(
    package: str, class_name: str, class_name_lower: str, topics_str: str
) -> str:
    """Generate Java consumer listener."""
    return f'''package {package}.listener;

import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.common.header.Headers;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.tinkoff.kora.common.Component;
import ru.tinkoff.kora.kafka.common.annotation.KafkaListener;

/**
 * Kafka consumer listener for topics: {topics_str}
 * Generated by kora-kafka generator
 */
@Component
public final class {class_name} {{

    private static final Logger log = LoggerFactory.getLogger({class_name}.class);

    /**
     * Simple value processing.
     * Auto-commits after each message.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processValue(String value) {{
        log.info("Received value: {{}}", value);
        // TODO: Implement business logic
    }}

    /**
     * Key-value pair processing.
     * Auto-commits after each message.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processKeyValue(String key, String value) {{
        log.info("Received key={{}}, value={{}}", key, value);
        // TODO: Implement business logic
    }}

    /**
     * Processing with access to headers.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processWithHeaders(String key, String value, Headers headers) {{
        log.info("Received key={{}}, value={{}}", key, value);
        // TODO: Implement business logic with headers
    }}

    /**
     * Processing with full ConsumerRecord access.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processRecord(ConsumerRecord<String, String> record) {{
        log.info("Received topic={{}}, partition={{}}, offset={{}}",
            record.topic(), record.partition(), record.offset());
        // TODO: Implement business logic
    }}

    /**
     * Batch processing with ConsumerRecords.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processRecords(ConsumerRecords<String, String> records) {{
        log.info("Received batch of {{}} records", records.count());
        for (ConsumerRecord<String, String> record : records) {{
            // TODO: Process each record
        }}
    }}

    /**
     * Processing with manual offset commit.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processWithManualCommit(ConsumerRecord<String, String> record, Consumer<String, String> consumer) {{
        try {{
            log.info("Processing record: offset={{}}", record.offset());
            // TODO: Implement business logic
            consumer.commitSync();
        }} catch (Exception e) {{
            log.error("Processing failed", e);
            // Don't commit - message will be retried
        }}
    }}
}}
'''


def generate_java_json_listener(
    package: str, class_name: str, class_name_lower: str, event_name: str, topics_str: str
) -> str:
    """Generate Java JSON consumer listener."""
    return f'''package {package}.listener;

import jakarta.annotation.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.tinkoff.kora.common.Component;
import ru.tinkoff.kora.json.common.annotation.Json;
import ru.tinkoff.kora.kafka.common.annotation.KafkaListener;

import java.time.LocalDateTime;

/**
 * Kafka consumer listener with JSON deserialization for topics: {topics_str}
 * Generated by kora-kafka generator
 */
@Component
public final class {class_name} {{

    private static final Logger log = LoggerFactory.getLogger({class_name}.class);

    /**
     * Event DTO for JSON deserialization.
     */
    @Json
    public record {event_name}(
        String id,
        String eventType,
        String payload,
        LocalDateTime timestamp
    ) {{}}

    /**
     * Process JSON event (value only).
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processEvent(@Json {event_name} event) {{
        log.info("Received event: id={{}}, type={{}}", event.id(), event.eventType());
        // TODO: Implement business logic
        switch (event.eventType()) {{
            case "created" -> handleCreated(event);
            case "updated" -> handleUpdated(event);
            case "deleted" -> handleDeleted(event);
            default -> log.warn("Unknown event type: {{}}", event.eventType());
        }}
    }}

    /**
     * Process JSON event with key.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processEventWithKey(String key, @Json {event_name} event) {{
        log.info("Received key={{}}, event: id={{}}", key, event.id());
        // TODO: Implement business logic
        processEvent(event);
    }}

    /**
     * Process JSON event with error handling.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    void processEventWithErrorHandling(@Nullable @Json {event_name} event, @Nullable Exception error) {{
        if (error != null) {{
            log.error("Failed to deserialize event", error);
            // TODO: Handle error (send to DLQ, log, etc.)
            return;
        }}
        if (event == null) {{
            log.warn("Received null event without error");
            return;
        }}
        // TODO: Implement business logic
        processEvent(event);
    }}

    private void handleCreated({event_name} event) {{
        log.info("Handling created event: {{}}", event.id());
        // TODO: Implement creation logic
    }}

    private void handleUpdated({event_name} event) {{
        log.info("Handling updated event: {{}}", event.id());
        // TODO: Implement update logic
    }}

    private void handleDeleted({event_name} event) {{
        log.info("Handling deleted event: {{}}", event.id());
        // TODO: Implement deletion logic
    }}
}}
'''


def generate_kotlin_consumer(
    package: str, class_name: str, class_name_lower: str, topics_str: str
) -> str:
    """Generate Kotlin consumer listener."""
    return f'''package {package}.listener

import org.apache.kafka.clients.consumer.Consumer
import org.apache.kafka.clients.consumer.ConsumerRecord
import org.apache.kafka.clients.consumer.ConsumerRecords
import org.apache.kafka.common.header.Headers
import org.slf4j.LoggerFactory
import ru.tinkoff.kora.common.Component
import ru.tinkoff.kora.kafka.common.annotation.KafkaListener

/**
 * Kafka consumer listener for topics: {topics_str}
 * Generated by kora-kafka generator
 */
@Component
class {class_name} {{

    private val log = LoggerFactory.getLogger({class_name}::class.java)

    /**
     * Simple value processing.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processValue(value: String) {{
        log.info("Received value: {{}}", value)
        // TODO: Implement business logic
    }}

    /**
     * Key-value pair processing.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processKeyValue(key: String, value: String) {{
        log.info("Received key={{}}, value={{}}", key, value)
        // TODO: Implement business logic
    }}

    /**
     * Processing with access to headers.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processWithHeaders(key: String, value: String, headers: Headers) {{
        log.info("Received key={{}}, value={{}}", key, value)
        // TODO: Implement business logic with headers
    }}

    /**
     * Processing with full ConsumerRecord access.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processRecord(record: ConsumerRecord<String, String>) {{
        log.info(
            "Received topic={{}}, partition={{}}, offset={{}}",
            record.topic(),
            record.partition(),
            record.offset()
        )
        // TODO: Implement business logic
    }}

    /**
     * Batch processing with ConsumerRecords.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processRecords(records: ConsumerRecords<String, String>) {{
        log.info("Received batch of {{}} records", records.count())
        for (record in records) {{
            // TODO: Process each record
        }}
    }}

    /**
     * Processing with manual offset commit.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processWithManualCommit(record: ConsumerRecord<String, String>, consumer: Consumer<String, String>) {{
        try {{
            log.info("Processing record: offset={{}}", record.offset())
            // TODO: Implement business logic
            consumer.commitSync()
        }} catch (e: Exception) {{
            log.error("Processing failed", e)
            // Don't commit - message will be retried
        }}
    }}
}}
'''


def generate_kotlin_json_listener(
    package: str, class_name: str, class_name_lower: str, event_name: str, topics_str: str
) -> str:
    """Generate Kotlin JSON consumer listener."""
    return f'''package {package}.listener

import jakarta.annotation.Nullable
import org.slf4j.LoggerFactory
import ru.tinkoff.kora.common.Component
import ru.tinkoff.kora.json.common.annotation.Json
import ru.tinkoff.kora.kafka.common.annotation.KafkaListener
import java.time.LocalDateTime

/**
 * Kafka consumer listener with JSON deserialization for topics: {topics_str}
 * Generated by kora-kafka generator
 */
@Component
class {class_name} {{

    private val log = LoggerFactory.getLogger({class_name}::class.java)

    /**
     * Event data class for JSON deserialization.
     */
    @Json
    data class {event_name}(
        val id: String,
        val eventType: String,
        val payload: String,
        val timestamp: LocalDateTime
    )

    /**
     * Process JSON event (value only).
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processEvent(event: {event_name}) {{
        log.info(
            "Received event: id={{}}, type={{}}",
            event.id,
            event.eventType
        )
        // TODO: Implement business logic
        when (event.eventType) {{
            "created" -> handleCreated(event)
            "updated" -> handleUpdated(event)
            "deleted" -> handleDeleted(event)
            else -> log.warn("Unknown event type: {{}}", event.eventType)
        }}
    }}

    /**
     * Process JSON event with key.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processEventWithKey(key: String, event: {event_name}) {{
        log.info("Received key={{}}, event: id={{}}", key, event.id)
        // TODO: Implement business logic
        processEvent(event)
    }}

    /**
     * Process JSON event with error handling.
     */
    @KafkaListener("kafka.consumer.{class_name_lower}")
    fun processEventWithErrorHandling(@Nullable event: {event_name}?, @Nullable error: Exception?) {{
        if (error != null) {{
            log.error("Failed to deserialize event", error)
            // TODO: Handle error (send to DLQ, log, etc.)
            return
        }}
        if (event == null) {{
            log.warn("Received null event without error")
            return
        }}
        // TODO: Implement business logic
        processEvent(event)
    }}

    private fun handleCreated(event: {event_name}) {{
        log.info("Handling created event: {{}}", event.id)
        // TODO: Implement creation logic
    }}

    private fun handleUpdated(event: {event_name}) {{
        log.info("Handling updated event: {{}}", event.id)
        // TODO: Implement update logic
    }}

    private fun handleDeleted(event: {event_name}) {{
        log.info("Handling deleted event: {{}}", event.id)
        // TODO: Implement deletion logic
    }}
}}
'''


def generate_java_tests(
    package: str, class_name: str, class_name_lower: str, topic: str
) -> str:
    """Generate Java test class."""
    return f'''package {package}.listener;

import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.kafka.common.serialization.StringSerializer;
import org.assertj.core.api.Assertions;
import org.jetbrains.annotations.NotNull;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.KafkaContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;
import org.testcontainers.shaded.org.awaitility.Awaitility;
import ru.tinkoff.kora.application.graph.Lifecycle;
import ru.tinkoff.kora.common.Tag;
import ru.tinkoff.kora.test.extension.junit5.*;

import java.time.Duration;
import java.util.Properties;
import java.util.concurrent.Executors;

/**
 * Integration tests for {class_name} using Testcontainers Kafka.
 *
 * Usage:
 * 1. Make sure the dependencies are added in build.gradle:
 *    testImplementation "org.testcontainers:junit-jupiter:1.21.4"
 *    testImplementation "org.testcontainers:kafka:1.21.4"
 *    testImplementation "ru.tinkoff.kora:kafka"
 *    testImplementation "org.json:json:20231013"
 *    testImplementation "org.awaitility:awaitility:4.2.0"
 *
 * 2. Run tests: ./gradlew test
 */
@Testcontainers
@KoraAppTest(Application.class)
class {class_name}Tests implements KoraAppTestConfigModifier {{

    @Container
    static final KafkaContainer KAFKA = new KafkaContainer(
        DockerImageName.parse("confluentinc/cp-kafka:7.5.0")
    ).withStartupTimeout(Duration.ofSeconds(60));

    @Tag({class_name}Module.{class_name}ProcessTag.class)
    @TestComponent
    private Lifecycle consumerLifecycle;

    @TestComponent
    private {class_name} consumer;

    @NotNull
    @Override
    public KoraConfigModification config() {{
        return KoraConfigModification.ofString("""
            kafka.consumer.{class_name_lower} {{
                topics = ["{topic}"]
                offset = "earliest"
                pollTimeout = "5s"
                driverProperties {{
                    "bootstrap.servers" = "${{KAFKA_BOOTSTRAP_SERVERS}}"
                    "group.id" = "{class_name_lower}-test-group"
                    "auto.offset.reset" = "earliest"
                    "enable.auto.commit" = "true"
                }}
            }}
            """)
            .withSystemProperty("KAFKA_BOOTSTRAP_SERVERS", KAFKA.getBootstrapServers());
    }}

    @BeforeEach
    void setUp() {{
        // Reset consumer state before each test if needed
    }}

    @Test
    void shouldProcessEvent() {{
        // given
        var event = new JSONObject()
            .put("id", "test-123")
            .put("eventType", "created")
            .put("payload", "{{}}")
            .put("timestamp", java.time.LocalDateTime.now().toString());

        // when
        sendKafkaMessage("{topic}", event.toString());

        // then
        Awaitility.await()
            .atMost(Duration.ofSeconds(15))
            .pollExecutorService(Executors.newSingleThreadExecutor())
            .until(() -> consumer.getProcessedCount() >= 1);
    }}

    @Test
    void shouldProcessMultipleEvents() {{
        // given
        int eventCount = 5;
        for (int i = 0; i < eventCount; i++) {{
            var event = new JSONObject()
                .put("id", "test-" + i)
                .put("eventType", "created")
                .put("payload", "{{}}")
                .put("timestamp", java.time.LocalDateTime.now().toString());
            sendKafkaMessage("{topic}", event.toString());
        }}

        // when & then
        Awaitility.await()
            .atMost(Duration.ofSeconds(20))
            .pollExecutorService(Executors.newSingleThreadExecutor())
            .until(() -> consumer.getProcessedCount() >= eventCount);
    }}

    @Test
    void shouldHandleInvalidJson() {{
        // given - invalid JSON
        String invalidJson = "{{\\"id\\": \\"test-invalid\\"}}";

        // when
        sendKafkaMessage("{topic}", invalidJson);

        // then - should handle without crashing
        Awaitility.await()
            .atMost(Duration.ofSeconds(10))
            .until(() -> consumer.getErrorCount() >= 0);
    }}

    /**
     * Send a Kafka message without key.
     */
    private void sendKafkaMessage(String topic, String value) {{
        var props = new Properties();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, KAFKA.getBootstrapServers());

        try (var producer = new KafkaProducer<>(
            props,
            new StringSerializer(),
            new StringSerializer()
        )) {{
            producer.send(new ProducerRecord<>(topic, value));
        }}
    }}
}}
'''


def generate_kotlin_tests(
    package: str, class_name: str, class_name_lower: str, topic: str
) -> str:
    """Generate Kotlin test class."""
    return f'''package {package}.listener

import org.apache.kafka.clients.consumer.ConsumerConfig
import org.apache.kafka.clients.producer.KafkaProducer
import org.apache.kafka.clients.producer.ProducerRecord
import org.apache.kafka.common.serialization.StringDeserializer
import org.apache.kafka.common.serialization.StringSerializer
import org.assertj.core.api.Assertions.assertThat
import org.jetbrains.annotations.NotNull
import org.json.JSONObject
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.testcontainers.containers.KafkaContainer
import org.testcontainers.junit.jupiter.Container
import org.testcontainers.junit.jupiter.Testcontainers
import org.testcontainers.utility.DockerImageName
import org.testcontainers.shaded.org.awaitility.Awaitility
import ru.tinkoff.kora.application.graph.Lifecycle
import ru.tinkoff.kora.common.Tag
import ru.tinkoff.kora.test.extension.junit5.*
import java.time.Duration
import java.util.Properties
import java.util.concurrent.Executors

/**
 * Integration tests for {class_name} using Testcontainers Kafka.
 *
 * Usage:
 * 1. Make sure the dependencies are added in build.gradle.kts:
 *    testImplementation("org.testcontainers:junit-jupiter:1.21.4")
 *    testImplementation("org.testcontainers:kafka:1.21.4")
 *    testImplementation("ru.tinkoff.kora:kafka")
 *    testImplementation("org.json:json:20231013")
 *    testImplementation("org.awaitility:awaitility:4.2.0")
 *
 * 2. Run tests: ./gradlew test
 */
@Testcontainers
@KoraAppTest(Application::class)
class {class_name}Tests : KoraAppTestConfigModifier {{

    companion object {{
        @Container
        @JvmStatic
        val KAFKA = KafkaContainer(
            DockerImageName.parse("confluentinc/cp-kafka:7.5.0")
        ).withStartupTimeout(Duration.ofSeconds(60))
    }}

    @Tag({class_name}Module.{class_name}ProcessTag::class)
    @TestComponent
    private lateinit var consumerLifecycle: Lifecycle

    @TestComponent
    private lateinit var consumer: {class_name}

    @NotNull
    override fun config(): KoraConfigModification {{
        return KoraConfigModification.ofString("""
            kafka.consumer.{class_name_lower} {{
                topics = ["{topic}"]
                offset = "earliest"
                pollTimeout = "5s"
                driverProperties {{
                    "bootstrap.servers" = "${{KAFKA.bootstrapServers}}"
                    "group.id" = "{class_name_lower}-test-group"
                    "auto.offset.reset" = "earliest"
                    "enable.auto.commit" = "true"
                }}
            }}
            """.trimIndent())
            .withSystemProperty("KAFKA_BOOTSTRAP_SERVERS", KAFKA.bootstrapServers)
    }}

    @BeforeEach
    fun setUp() {{
        // Reset consumer state before each test if needed
    }}

    @Test
    fun `should process event`() {{
        // given
        val event = JSONObject()
            .put("id", "test-123")
            .put("eventType", "created")
            .put("payload", "{{}}")
            .put("timestamp", java.time.LocalDateTime.now().toString())

        // when
        sendKafkaMessage("{topic}", event.toString())

        // then
        Awaitility.await()
            .atMost(Duration.ofSeconds(15))
            .pollExecutorService(Executors.newSingleThreadExecutor())
            .until {{ consumer.processedCount >= 1 }}
    }}

    @Test
    fun `should process multiple events`() {{
        // given
        val eventCount = 5
        for (i in 0 until eventCount) {{
            val event = JSONObject()
                .put("id", "test-$i")
                .put("eventType", "created")
                .put("payload", "{{}}")
                .put("timestamp", java.time.LocalDateTime.now().toString())
            sendKafkaMessage("{topic}", event.toString())
        }}

        // when & then
        Awaitility.await()
            .atMost(Duration.ofSeconds(20))
            .pollExecutorService(Executors.newSingleThreadExecutor())
            .until {{ consumer.processedCount >= eventCount }}
    }}

    @Test
    fun `should handle invalid json`() {{
        // given - invalid JSON
        val invalidJson = """{{"id": "test-invalid"}}"""

        // when
        sendKafkaMessage("{topic}", invalidJson)

        // then - should handle without crashing
        Awaitility.await()
            .atMost(Duration.ofSeconds(10))
            .until {{ consumer.errorCount >= 0 }}
    }}

    /**
     * Send a Kafka message without key.
     */
    private fun sendKafkaMessage(topic: String, value: String) {{
        val props = Properties().apply {{
            put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, KAFKA.bootstrapServers)
        }}

        KafkaProducer<String, String>(
            props,
            StringSerializer(),
            StringSerializer()
        ).use {{ producer ->
            producer.send(ProducerRecord(topic, value))
        }}
    }}
}}
'''


def generate_config(
    listener_name: str,
    topics_str: str,
    topics_pattern: str,
    group_id: str,
    package: str,
) -> str:
    """Generate application.conf configuration."""
    return f'''# Kora Kafka Consumer Configuration
# Generated by kora-kafka generator

kafka {{
  consumer {{
    {listener_name} {{
      # Topics to consume from
      topics = [{topics_str}]
      # Alternative: Subscribe by pattern
      # topicsPattern = "{topics_pattern}"

      # Consumer behavior
      offset = "earliest"
      pollTimeout = "5s"
      backoffTimeout = "15s"
      threads = 1
      shutdownWait = "30s"

      # Kafka driver properties
      driverProperties {{
        "bootstrap.servers" = ${{KAFKA_BOOTSTRAP_SERVERS:"localhost:9092"}}
        "group.id" = "{group_id}"
        "auto.offset.reset" = "earliest"
        "enable.auto.commit" = true
        "max.poll.records" = 500
      }}

      # Telemetry
      telemetry {{
        logging {{
          enabled = true
        }}
        metrics {{
          enabled = true
          slo = [1, 10, 50, 100, 200, 500, 1000, 2000, 5000, 10000]
          tags = {{
            "consumer-type" = "{listener_name}"
          }}
        }}
        tracing {{
          enabled = true
          attributes = {{
            "service.name" = "{package}.service"
          }}
        }}
      }}
    }}
  }}
}}
'''


def main():
    parser = argparse.ArgumentParser(
        description="Generate Kora Kafka consumer listener"
    )
    parser.add_argument(
        "--name", "-n", required=True, help="Listener class name (e.g., UserEventListener)"
    )
    parser.add_argument(
        "--topics", "-t", required=True, help="Comma-separated list of topics"
    )
    parser.add_argument(
        "--package", "-p", default="com.example", help="Package name"
    )
    parser.add_argument(
        "--lang", "-l", choices=["java", "kotlin"], default="java", help="Language"
    )
    parser.add_argument(
        "--output", "-o", default=".", help="Output directory"
    )
    parser.add_argument(
        "--tests", action="store_true", help="Generate tests"
    )
    parser.add_argument(
        "--json", action="store_true", help="Generate JSON listener with @Json"
    )
    parser.add_argument(
        "--event-name", help="Event class name for JSON listeners"
    )
    parser.add_argument(
        "--group-id", help="Consumer group ID"
    )

    args = parser.parse_args()

    topics = [t.strip() for t in args.topics.split(",")]

    generate_consumer(
        name=args.name,
        topics=topics,
        package=args.package,
        lang=args.lang,
        output_dir=args.output,
        with_tests=args.tests,
        is_json=args.json,
        event_name=args.event_name,
        consumer_group_id=args.group_id,
    )

    print("\nGenerated successfully!")
    print("\nNext steps:")
    print("1. Review and customize the listener class")
    print("2. Add configuration to application.conf")
    print("3. Implement business logic")
    print("4. Run tests: ./gradlew test")


if __name__ == "__main__":
    main()
